project:
  type: book

book:
  title: "Vigie-Nature Data Catalogue"

  author:
    - name: "Charles Thévenin"
      orcid: ""
      affiliations:
        - name: Vigie-Nature
          url: "https://www.vigienature.fr/fr"


  date: today
  description:  |
    Description des exports de données des observatoires Vigie-Nature
    <br /><br />

#  favicon: images/favicon.png

  sidebar:
    style: "docked"
    collapse-level: 1

  page-footer:
    left: "&copy; CC BY 4.0 [Vigie-Nature](https://www.vigienature.fr/fr)"
    # center: "Code source available on [{{< fa brands github >}}](https://github.com/rdatatoolbox/rdatatoolbox.github.io/)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true

  reader-mode: false
  search: false

  chapters:
    - index.qmd
    # - chapters/setting-up-r.qmd
    - part: "Introduction"
      chapters:
        - chapters/intro-informations.qmd
        - chapters/intro-standardisation.qmd
        - chapters/intro-gettingstarted.qmd
    - part: "Datasets"
      chapters:
        - chapters/data-oab.qmd
        - chapters/data-spipoll.qmd
        - chapters/data-steli.qmd
        - chapters/data-sterf.qmd
    - part: "Resources"
      chapters:
        - chapters/references.qmd
    #    - chapters/wrap-up.qmd

format:
  html:
    theme: [cosmo, css/styles.scss]
    code-copy: true
    code-line-numbers: false