# Scripts d'export de données

<br>

Chaque export de données s'effectue grâce à différentes tâches centralisées dans un script dédié au sein du dossier `analyse`.

Le script correspondant doit permettre d'effectuer les tâches suivantes :

-   **Importer les données brutes** comme dataframe dans l'environnement gobal R

-   **Standardiser les noms des champs** là où nécessaire afin d'homogénéiser les exports (session, observation, user, etc...) et appliquer les formatages nécessaires (ex : format de dates en `YYYY-MM-DD`)

-   Corriger les problèmes de **valeurs aberrantes** là où nécessaire (ex : dates de sessions antérieures au lancement de l'observatoire, remplacer les `"null"`/`"NULL"` en `NA`)

-   Appliquer et documenter les **filtres spécifiques à l'observatoire** (valeurs d'abondances aberrantes, taxons hors liste, anonymisation, observations en dehors du territoire de France hexagonale, occurrences à ne pas diffuser, etc...)

<br>

## Importer les données brutes

Deux possibilités selon les modalités d'accès aux données :

- Import depuis un fichier `.csv` contenant un export de données "brutes" stocké dans le sous-répertoire `/data/input`.

- Import des données via l'envoi d'une requête SQL dans le cas de Vigie-Nature école ou des bases de données hébergées chez Mosaic. Les requêtes sont placées dans le sous-répertoire `/sql`

<br>

## Standardisation des exports

### Harmonisation des termes utilisés :

-   `session` correspond à la participation, c'est-à-dire l'application du protocole par une personne à un moment donné (une collection Spipoll, un relevé Vigie-Flore, une partie Birdlab...). Une `session` d'observation doit systématiquement être associée à un identifiant unique (`session_id`) et à une date (`session_date`), et parfois à une heure de début et de fin (`session_starting_time`)

-   `observation` correspond à l'observation d'un taxon, et est associé à un identifiant unique (`observation_id`). Une session peut comporter une ou plusieurs observations. Les exports à plat peuvent contenir des sessions "vides" : aucun organisme n'a été observé et le champ `observation_id` sera vide.

-   `site` permet d'identifier le lieu où a été effectuée la session d'observation. Le site doit être associé à des coordonnées géographiques en WGS 84.

-   `latitude` & `longitude` : afin de faciliter la synthèse des données l'export à plat doit associer un couple de coordonnées XY à chaque session. Dans la plupart des cas il s'agît simplement des coordonnées du point d'observation. Néanmoins certains protocoles se basent sur d'autres unités spatiales d'échantillonnage (transect, point d'observation, quadrat...), et dans ce cas là les valeurs correspondront au barycentre de la ligne ou du polygone.

-   `taxon` fournit l'information sur l'organisme ou le groupe d'organisme observé. Le `taxon` peut-être associé à une valeur de comptage (`taxon_count`) qui peut être une abondance ou un nombre de contacts. Si la valeur décrite dans `taxon_count` n'est pas un nombre d'individus alors le type doit être spécifié dans un champ `taxon_count_description`. Les exports à plat peuvent contenir des sessions "vides" : aucun organisme n'a été observé et le champ `taxon` sera vide.

### Liste des noms des champs obligatoires

::: callout-important
CHAQUE EXPORT DE DONNEES DOIT COMPRENDRE L'ENSEMBLE DES CHAMPS CI-DESSOUS
:::

| Nom du champ | Description | Valeurs aberrantes |
|------------------|-----------------------------------|-------------------|
| session_id | Identifiant unique de la session d'observation | Ne peut être NA |
| session_date | Date de la session d'observation, au format YYYY-MM-DD | Ne peut être NA |
| observation_id | Identifiant unique de l'observation | Peut être NA si aucun organisme n'a été observée lors de la session |
| user_id | Identifiant unique de la personne ayant effectué l'observation | Ne peut être NA |
| taxon | Nom de l'espèce, du groupe d'espèce ou du type d'organisme observé | Peut être NA si aucun organisme n'a été observé lors de la session |
| longitude | Longitude du site d'observation (la valeur exacte pour un point d'observation, le barycentre pour un transect ou un polygone) | Ne peut être NA |
| latitude | Latitude du site d'observation (la valeur exacte pour un point d'observation, le barycentre pour un transect ou un polygone) | Ne peut être NA |

<br>

## Formatage des exports

-   `session_date` au format `YYYY-MM-DD`

-   si absente du jeu de données, ajouter la colonne `session_year` correspondant à l'année de la session

-   `latitude` & `longitude` en projection WGS84

