name: Build Quarto book

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mpretet/image_fiche_opj:4.4.2
      
    steps:
      # Récupération du code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render book
        run: quarto render

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
